// angular/programs/angularbasics/src/app/components/simpleinterest/simpleinterest.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-simpleinterest',
  templateUrl: './simpleinterest.component.html',
  styleUrls: ['./simpleinterest.component.css']
})
export class SimpleinterestComponent implements OnInit {

  principal:number | any;
  roi:number|any;
  time:number|any;
  si:number|any;
  
  constructor() { }

  ngOnInit(): void {
  }

  CalculateSI():void{
    this.si = (this.principal*this.roi*this.time)/100;
  }

}

<h1>Simple Interest</h1>

<label>Enter Principal Amount</label><br>
<input type="text" [(ngModel)]="principal" name="principal"><br>
<label>Enter Rate Of Interest</label><br>
<input type="text" [(ngModel)]="roi" name="roi"><br>
<label>Enter Time in Years</label><br>
<input type="text" [(ngModel)]="time" name="time"><br>
<button (click)="CalculateSI()">Calculate</button>
<h1>Simple Interest is {{si}}</h1>

// react/reacttraining/reactbasics/src/components/SimpleInterest.js
import React,{useState} from 'react'
export const SimpleInterest = () => {
    const [principal,setPrincipal] =useState()
    const [rate,setRate] =useState()
    const [time,setTime] =useState()
    const [si,setSi] =useState()
    const calculateInterest=()=>{
        let simpleInterest = (parseFloat(principal)*parseFloat(rate)*parseFloat(time))/100
        setSi(simpleInterest)
    }
return (
    <div>
    <input value={principal} onChange={(e)=>{setPrincipal(e.target.value)}} placeholder="Enter Principal"/>
    <input value={rate} onChange={(e)=>{setRate(e.target.value)}} placeholder="Enter Rate of Interest"/>
    <input value={time} onChange={(e)=>{setTime(e.target.value)}} placeholder="Enter Time in years"/>
    <button onClick={calculateInterest}>Calculate</button>
    <h1>Simple Interest is {si}</h1>

    </div>
  )
}
